hafahvac/admin/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import InputRequired
from flask_wtf.file import FileField, FileRequired
from wtforms import PasswordField, SubmitField, StringField, TextAreaField

class SecretForm(FlaskForm):
    password = PasswordField('Name')
    submit = SubmitField('Login')

class CarouselForm(FlaskForm):
    image = FileField([FileRequired()])
    title = StringField('Title', [InputRequired()])
    description = TextAreaField('body')
    submit = SubmitField('Submit')

class PhotoForm(FlaskForm):
    image = FileField([FileRequired()])
    title = StringField('Title', [InputRequired()])
    description = TextAreaField('body')
    submit = SubmitField('Submit')

class DeleteForm(FlaskForm):
    id_to_delete = StringField('Delete', [InputRequired()])  
    submit = SubmitField('Submit')  

hafahvac/site/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, TextAreaField, DecimalField
from wtforms.validators import DataRequired, Length, Email, EqualTo

class ContactForm(FlaskForm):
    name = StringField('Name')
    email = StringField('Email', [DataRequired(), Email()])
    phone = StringField('Phone')
    body = TextAreaField('body', [DataRequired()])
    submit = SubmitField('Submit Inquery')

hafahvac/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
from hafahvac.config import Config

app = Flask(__name__)

@app.context_processor
def inject_globals():
    return dict(app_name="H&#8226;A&#8226;F&#8226;A HVAC")

app.config.from_object(Config)
db = SQLAlchemy(app)
mail = Mail(app)

db.init_app(app)

from hafahvac.errors.handlers import errors
from hafahvac.site.routes import site 
from hafahvac.legal.routes import legal
from hafahvac.admin.routes import admin

app.register_blueprint(errors)
app.register_blueprint(site)
app.register_blueprint(legal)
app.register_blueprint(admin)

hafahvac/admin/routes.py
from flask import flash, render_template, url_for, make_response, render_template, Blueprint, request, redirect
from hafahvac.admin.forms import SecretForm, CarouselForm, DeleteForm, PhotoForm
from hafahvac.admin.utils import admin_required, allowed_file
from models import Carousel, Photo
from hafahvac import db, app
from werkzeug import secure_filename

admin = Blueprint('admin', __name__)

@admin.route('/admin/login/',  methods=["GET", "POST"])
def admin_login():
    form = SecretForm()
    if form.validate_on_submit():
        if form.password.data == app.config["ADMIN_PASSWORD"]:
            response = make_response(redirect(url_for('admin.routes')))
            response.set_cookie("adminCookie", value = app.config["ADMIN_KEY"])
            return response
        else:
            flash("this password is incorrect!", "danger")
    return render_template('admin/login.html', title = "Admin Login", form = form)

@admin.route('/admin/',  methods=["GET", "POST"])
@admin_required
def routes():
    return render_template('admin/routes.html', title = "admin - routes")

@admin.route('/admin/carousel/',  methods=["GET", "POST"])
@admin_required
def carousel():
    form = CarouselForm()
    delete_form = DeleteForm()
    carousels = Carousel.query.all()
    if form.validate_on_submit():
        if allowed_file(form.image.data.filename):
            filename = secure_filename(form.image.data.filename)
            form.image.data.save('hafahvac/static/images/user-added-images/carousel/' + filename)
            description = ""
            if form.description.data:
                description = form.description.data
            new_image = Carousel(image_name = filename, title = form.title.data, body = description)
            db.session.add(new_image)
            db.session.commit()
            flash("file uploaded!", "success")
            return redirect(url_for('admin.carousel'))
        flash("this file extension is not allowed; only add images in .png, .jpg, .jpeg", "error")
    if delete_form.validate_on_submit():
        to_delete = Carousel.query.filter_by(id = delete_form.id_to_delete.data).first()
        if to_delete:
            db.session.delete(to_delete)
            db.session.commit()
            flash(f"Carousel image '{to_delete.title}' removed!", "success")
            return(redirect(url_for('admin.carousel')))
        else:
            flash(f"no image found with id '{delete_form.id_to_delete.data}'", "danger")
            return(redirect(url_for('admin.carousel')))
    return render_template('admin/carousel.html', title = "admin - carousel", form = form, delete_form = delete_form, carousels = carousels)

@admin.route('/admin/photos/',  methods=["GET", "POST"])
@admin_required
def photos():
    form = PhotoForm()
    delete_form = DeleteForm()
    photos = Photo.query.all()
    if form.validate_on_submit():
        if allowed_file(form.image.data.filename):
            filename = secure_filename(form.image.data.filename)
            form.image.data.save('hafahvac/static/images/user-added-images/photos/' + filename)
            description = ""
            if form.description.data:
                description = form.description.data
            new_image = Photo(image_name = filename, title = form.title.data, body = description)
            db.session.add(new_image)
            db.session.commit()
            flash("file uploaded!", "success")
            return redirect(url_for('admin.photos'))
        flash("this file extension is not allowed; only add images in .png, .jpg, .jpeg", "error")
    if delete_form.validate_on_submit():
        to_delete = Photo.query.filter_by(id = delete_form.id_to_delete.data).first()
        if to_delete:
            db.session.delete(to_delete)
            db.session.commit()
            flash(f"Photo '{to_delete.title}' removed!", "success")
            return(redirect(url_for('admin.photos')))
        else:
            flash(f"no image found with id '{delete_form.id_to_delete.data}'", "danger")
            return(redirect(url_for('admin.photos')))
    return render_template('admin/photos.html', title = "admin - photos", form = form, delete_form = delete_form, photos = photos)

hafahvac/legal/routes.py
from flask import Blueprint, render_template, jsonify

legal = Blueprint('legal', __name__)

@legal.route('/legal/cookiePolicy/')
def cookiePolicy():
    return render_template('cookiePolicy.html', title = "Cookie Policy")

hafahvac/site/routes.py
from flask import Blueprint, render_template, jsonify, flash, redirect, url_for, make_response, request
from hafahvac.site.forms import ContactForm
from hafahvac.site.utils import send_email
from hafahvac import db, app
from models import *

site = Blueprint('site', __name__)

@site.route('/',  methods=["GET", "POST"])
def index():
    form = ContactForm()
    carousels = Carousel.query.all()
    if form.validate_on_submit():
        phone = "(Not Entered)"
        if form.phone.data:
            phone = form.phone.data
        inquery = Contact(email = form.email.data, phone = phone, body = form.body.data)
        db.session.add(inquery)
        db.session.commit()
        send_email(form.email.data, form.body.data, form.phone.data)
        flash("Your message has been recived! please allow 24-48 business hours for a response.", "success")
        return redirect(url_for('site.index'))
    return render_template('index.html', title = "HAFA HVAC", form = form, carousels = carousels)

@site.route('/photos/')
def photos():
    photos = Photo.query.all()
    return render_template('photos.html', title = "HAFA HVAC - Photos", photos = photos)

@site.route('/contact/', methods=["GET", "POST"])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        inquery = Contact(email = form.email.data, phone = form.phone.data, body = form.body.data)
        db.session.add(inquery)
        send_email(form.email.data, form.body.data, form.phone.data)
        db.session.commit()
        flash("Your message has been recived! please allow 24-48 business hours for a response.", "success")
        return redirect(url_for('site.contact'))
    return render_template('contact.html', title = "HAFA HVAC - Contact", form = form)

hafahvac/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Lato|Patua+One&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <link href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet" type="text/css">
    <script src="{{ url_for('static', filename='js/cookiebar.js') }}"></script>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    {% block header %}
    {% endblock header %}
    <title>{{ title }}</title>
</head>

<body onload=checkAgreement()>
        {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for catagory, message in messages %}
                <div style = "position: absolute; width: 90vw; top: 4em; margin-left: 5vw;" class = "border border-{{ catagory }} rounded p-2 alert-{{ catagory }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div style="min-height: 95vh">
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary text-light" style="box-shadow: 0 1px 3px #ddd;">
            <a class="navbar-brand font-weight-bold  text-white ml-4" href="#">{{ app_name|safe }}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="basicExampleNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link my-1 mx-3" href="{{ url_for('site.index') }}">Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link my-1 mx-3" href="{{ url_for('site.photos') }}">Photos</a>
                    </li>
                </ul>
                <form class="form-inline">
                    <a class = "mr-4" href = "{{ url_for('site.contact') }}">
                    <button class="btn btn-secondary btn-block text-primary ml-3 px-3" style="border-radius: 2px;"
                        type="button">
                        Contact Us
                    </button>
                    </a>
                </form>
            </div>
        </nav>
            {% block main %}
            {% endblock main %}
        <div id="cookieBar">
            <div id="close_cookie" class="d-inline float-right pt-1 pr-3" style="font-size: 20px"
                onClick="closeCookieBar()">&#10005;</div>
            <p>
                By continuing to browse the site you are agreeing to our use of cookies.
                For more details about cookies see our <a class="text-white font-weight-bold"
                    href="{{ url_for('legal.cookiePolicy') }}"><u>cookie policy.</u></a>
            </p>
        </div>
    </div>
    <footer class="py-4 w-100 text-white">
        <div class="footer-grid">
            <div></div>
            <div class="widget no-box">
                <h5 class="widget-title">{{ app_name|safe }}<span></span></h5>
                <div class="header-accent">
                    <div class="top"></div>
                    <div class="bottom"></div>
                </div>
                <p class = "px-1">{{ app_name|safe }} is the most trusted HVAC company in the Antioch area.</p>
            </div>
            <div class="widget no-box">
                <h5 class="widget-title">Quick Links<span></span></h5>
                <div class="header-accent">
                    <div class="top"></div>
                    <div class="bottom"></div>
                </div>
                <ul class="list-unstyled text-primary">
                    <li><a href = "{{ url_for('site.index') }}">Home</a></li>
                    <li><a href = "{{ url_for('site.photos') }}">Photos</a></li>
                </ul>
            </div>
            <div></div>
            <div></div>
            <div class="widget no-box">
                <h5 class="widget-title">Get an appraisal today.<span></span></h5>
                <div class="header-accent">
                    <div class="top"></div>
                    <div class="bottom"></div>
                </div>
                <p class = "mr-3">Call during regular business hours, or click the contact link to schedule an appraisal.</p>
            </div>
            <div class="widget no-box">
                <h5 class="widget-title">Contact Us<span></span></h5>
                <div class="header-accent">
                    <div class="top"></div>
                    <div class="bottom"></div>
                </div>
                <p>
                    Got questions? Send an inquery.
                </p>
                <a href = "{{ url_for('site.contact') }}">
                    <button type="button" class="btn btn-primary" style="bottom: 0;">Contact</button>
                </a>
            </div>
        </div>
        <div></div>
    </footer>
</body>

</html>

hafahvac/templates/contact.html
{% extends 'base.html' %}
{% block header %}
{% endblock header %}
{% block main %}
<div class="mt-5 pt-5 px-2">
    <div class="text-center bg-light w-75 mx-auto p-2 m-5 border border-primary rounded" style="max-width: 500px;">
        <h3><small>Contact {{ app_name|safe }}</small></h3>
        <small>Any inqueries, questions, concerns, comments, can be placed here. if you'd prefer, you can make a call at
            <span class="text-dark">+1 (224) 727-8613.</span></small>
        <form class="p-3" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group row">
                <label class="col-2 col-form-label col-form-label">
                    Name:
                </label>
                <div class="col-sm-10">
                    {{ form.name(class = "form-control")}}
                </div>
                {% if form.name.errors %}
                <small class="text-danger">
                    {% for error in form.name.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </small>
                {% endif %}
            </div>
            <div class="form-group row">
                <label class="col-2 col-form-label col-form-label">
                    Email:
                </label>
                <div class="col-sm-10">
                    {{ form.email(class = "form-control")}}
                </div>
                {% if form.email.errors %}
                <small class="text-danger">
                    {% for error in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </small>
                {% endif %}
            </div>
            <div class="form-group row">
                <label class="col-2 col-form-label col-form-label">
                    Phone:
                </label>
                <div class="col-sm-10">
                    {{ form.phone(class = "form-control")}}
                </div>
                {% if form.phone.errors %}
                <small class="text-danger">
                    {% for error in form.name.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </small>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.body(rows = 3, class = "form-control") }}
                {% if form.body.errors %}
                <small class="text-danger">
                    {% for error in form.body.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </small>
                {% endif %}
            </div>
            {{ form.submit(class = "btn btn-primary btn-block p-3 mb-2 text-light")}}
        </form>
    </div>
</div>
{% endblock %}

hafahvac/templates/cookiePolicy.html
{% extends 'base.html' %}
{% block header %}
{% endblock header %}
{% block main %}
<div class = "mt-5 pt-5 px-2">
<div class = "mx-auto mb-5" style = "max-width: 500px;">
<h1 class = "text-center mb-5">Cookie Policy of {{ app_name }}</h1>
<div>
        <p>Cookies consist of portions of code installed in the browser that assist the Owner in providing the Service
                according to the purposes described. Some of the purposes for which Cookies are installed may also
                require the User's consent.
                Where the installation of Cookies is based on consent, such consent can be freely withdrawn at any time
                following the instructions provided in this document.</p>
        <h4 class = "mb-2">Other types of Cookies or third parties that install Cookies</h4>
        <p>
                Some of the services listed below collect statistics in an anonymized and aggregated form and may not
                require the consent of the User or may be managed directly by the Owner - depending on how they are
                described - without the help of third parties.

                If any third party operated services are listed among the tools below, these may be used to track Users’
                browsing habits – in addition to the information specified herein and without the Owner’s knowledge.
                Please refer to the privacy policy of the listed services for detailed information.
        </p>
        <h4 class = "mb-2">Advertising</h4>
        <p>
                This type of service allows User Data to be utilized for advertising communication purposes displayed in
                the form of banners and other advertisements on this Website, possibly based on User interests.
                This does not mean that all Personal Data are used for this purpose. Information and conditions of use
                are shown below.
                Some of the services listed below may use Cookies to identify Users or they may use the behavioral
                retargeting technique, i.e. displaying ads tailored to the User’s interests and behavior, including
                those detected outside this Website. For more information, please check the privacy policies of the
                relevant services.
        </p>
        <h4 class = "mb-2">Analytics</h4>
        <p>
                The services contained in this section enable the Owner to monitor and analyze web traffic and can be
                used to keep track of User behavior.

                Google Analytics (Google Inc.)
                Google Analytics is a web analysis service provided by Google Inc. (“Google”). Google utilizes the Data
                collected to track and examine the use of this Website, to prepare reports on its activities and share
                them with other Google services.
                Google may use the Data collected to contextualize and personalize the ads of its own advertising
                network.
                Personal Data collected: Cookies and Usage Data.

                Place of processing: United States – <a href="https://policies.google.com/privacy?hl=en">Privacy
                        Policy</a> – <a href="https://tools.google.com/dlpage/gaoptout?hl=en">Opt Out</a>. Privacy
                Shield participant.
        </p>
</div>
</div>
</div>
{% endblock main %}

hafahvac/templates/index.html
{% extends 'base.html' %}
{% block header %}
<link href="{{ url_for('static', filename='css/index.css') }}" rel="stylesheet" type="text/css">
{% endblock header %}
{% block main %}
<div id="splash" class="text-center text-primary"
    style="background-image: url({{ url_for('static', filename='images/main-splash.png') }});">
    <div class="bg-light" id="contact-form">
        <div class="bg-primary m-2 p-2"></div>
        <h3 class=" d-5 p-2 "><small>CONTACT US</small></h3>
        <p>To contact us, either fill out the form, or call <span class="text-dark">+1 (224) 727-8613.</span></p>
        <form class="p-3" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group row">
                <label class="col-2 col-form-label col-form-label">
                    Name:
                </label>
                <div class="col-sm-10">
                    {{ form.name(class = "form-control")}}
                </div>
                {% if form.name.errors %}
                <small class="text-danger">
                    {% for error in form.name.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </small>
                {% endif %}
            </div>
            <div class="form-group row">
                <label class="col-2 col-form-label col-form-label">
                    Email:
                </label>
                <div class="col-sm-10">
                    {{ form.email(class = "form-control")}}
                </div>
                {% if form.email.errors %}
                <small class="text-danger">
                    {% for error in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </small>
                {% endif %}
            </div>
            <div class="form-group row">
                <label class="col-2 col-form-label col-form-label">
                    Phone:
                </label>
                <div class="col-sm-10">
                    {{ form.phone(class = "form-control")}}
                </div>
                {% if form.phone.errors %}
                <small class="text-danger">
                    {% for error in form.name.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </small>
                {% endif %}
            </div>
            <div class = "form-group">
            {{ form.body(rows = 3, class = "form-control") }}
            {% if form.body.errors %}
                <small class="text-danger">
                    {% for error in form.body.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </small>
                {% endif %}
            </div>
            {{ form.submit(class = "btn btn-primary btn-block p-3 mb-2 text-light")}}
        </form>
    </div>
    <div class="text-light text-center m-2" style="display: flex; align-items: center;">
        <div class="mx-auto">
            <h1>{{ app_name|safe }}</h1>
            <h3>Kenosha, Lake County and Cook County Area HVAC Certified Heating and Air Conditioning</h3>
        </div>
    </div>
</div>
<div class="bg-dark w-100 p-5 text-light">
    <div id="carouselExampleControls" class="carousel slide mx-auto" style = "max-width: 500px" data-ride="carousel">
        <ol class="carousel-indicators">
            {% for carousel in carousels %}
            <li data-target="#carouselExampleControls" data-slide-to="loop.index0" {% if loop.index0 == 0 %}class="active"{% endif %}></li>
            {% endfor %}
        </ol>
        <div class="carousel-inner">
            {% for carousel in carousels %}
            <div class="carousel-item {% if loop.index == 1 %}active{% endif %}">
                <img class="mx-auto d-block w-100" src="{{ url_for('static', filename='images/user-added-images/carousel/' + carousel.image_name) }}"
                    alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5>{{ carousel.title }}</h5>
                    <p>{{ carousel.body }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
<div class="text-center text-primary">
    <h2><small>Our HVAC services</small></h2>
    <div class="long-underline bg-primary"></div>
    <p class="mt-3">{{ app_name|safe }} does everything HVAC. You name it. Done on time and on budget. We are properly
        HVAC certified.</p>
    <div class="text-center" id="service-grid">
        <div>
            Heating
            <img class="d-block mx-auto mt-4"
                src="{{ url_for('static', filename='images/service-icons/heating.png') }}">
        </div>
        <div>
            Plumbing
            <img class="d-block mx-auto mt-4"
                src="{{ url_for('static', filename='images/service-icons/plumbing.png') }}">
        </div>
        <div>
            Air Conditioning
            <img class="d-block mx-auto mt-4"
                src="{{ url_for('static', filename='images/service-icons/air-condition.png') }}">
        </div>
        <div>
            Duct Work
            <img class="d-block mx-auto mt-4" src="{{ url_for('static', filename='images/service-icons/duct.png') }}">
        </div>
        <div>
            Water Heaters
            <img class="d-block mx-auto mt-4"
                src="{{ url_for('static', filename='images/service-icons/water-heater.png') }}">
        </div>
        <div>
            Heaters
            <img class="d-block mx-auto mt-4" src="{{ url_for('static', filename='images/service-icons/heater.png') }}">
        </div>
    </div>
</div>

{% endblock %}

hafahvac/templates/photos.html
{% extends 'base.html' %}
{% block header %}
<link href="{{ url_for('static', filename='css/photos.css') }}" rel="stylesheet" type="text/css">
{% endblock header %}
{% block main %}
<div class="mt-5 pt-5 px-2">
     <h1 class="text-primary text-center">Photos</h1>
    {% for photo in photos %}
    <div class="p-3">
        <div class="photo-card p-3 border border-primary bg-light">
            <img class="img-box rounded" src="{{ url_for('static', filename='images/user-added-images/photos/' + photo.image_name) }}">
            <div class="photo-card-description p-3">
                <h3>{{ photo.title }}</h3>
                <p class="d-inline">{{ photo.body }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}